# Generated by Django 5.1.7 on 2025-05-25 09:47

import chart_snapshots.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_journal', '0002_alter_tradejournalattachment_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSnapshotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-defined name for this configuration (e.g., EURUSD Daily EMA Setup)', max_length=255)),
                ('symbol', models.CharField(help_text='Symbol for the chart (e.g., EURUSD, BINANCE:BTCUSDT)', max_length=50)),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('3m', '3 Minutes'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('2h', '2 Hours'), ('4h', '4 Hours'), ('1D', 'Daily'), ('1W', 'Weekly'), ('1M', 'Monthly')], default='1D', max_length=3)),
                ('indicator_settings', models.JSONField(default=chart_snapshots.models.ChartSnapshotConfig.get_default_indicator_settings)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_snapshot_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Snapshot Configuration',
                'verbose_name_plural': 'Chart Snapshot Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Symbol at the time of snapshot (denormalized for quick access)', max_length=50)),
                ('timeframe', models.CharField(help_text='Timeframe at the time of snapshot (denormalized)', max_length=3)),
                ('snapshot_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the snapshot was generated and stored')),
                ('notes', models.TextField(blank=True, help_text='Optional user notes for this snapshot', null=True)),
                ('attachment', models.OneToOneField(help_text='Link to the stored image file in TradeJournalAttachment', on_delete=django.db.models.deletion.CASCADE, related_name='chart_snapshot_details', to='trade_journal.tradejournalattachment')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Associated journal entry, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_snapshots', to='trade_journal.tradejournal')),
                ('config', models.ForeignKey(blank=True, help_text='Configuration used for this snapshot, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='chart_snapshots.chartsnapshotconfig')),
            ],
            options={
                'verbose_name': 'Chart Snapshot',
                'verbose_name_plural': 'Chart Snapshots',
                'ordering': ['-snapshot_time'],
            },
        ),
    ]
