# Generated by Django 5.1.7 on 2025-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_snapshots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartsnapshotconfig',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='chartsnapshotconfig',
            name='timeframe',
        ),
        migrations.AlterField(
            model_name='chartsnapshotconfig',
            name='name',
            field=models.CharField(help_text='User-defined name for this indicator template (e.g., Standard EMAs & DMI)', max_length=255),
        ),
    ]
