# Generated by Django 5.1.7 on 2025-06-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_snapshots', '0002_remove_chartsnapshotconfig_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartsnapshotconfig',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, this template is accessible by all users.'),
        ),
    ]
