# Generated by Django 5.1.7 on 2025-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='instrument_symbol',
            field=models.CharField(blank=True, default='', help_text='The trading instrument symbol this bot targets, e.g., EUR_USD, XAUUSD', max_length=50),
        ),
    ]
