# Generated by Django 5.1.7 on 2025-08-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='random_seed',
            field=models.PositiveIntegerField(blank=True, help_text='Seed for any random operations to ensure reproducibility.', null=True),
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='runtime_fingerprint',
            field=models.JSONField(blank=True, help_text='Versions of code and libraries used for this run.', null=True),
        ),
    ]
