# Generated by Django 5.1.7 on 2025-07-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestconfig',
            name='timeframe',
            field=models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day')], default='M1', help_text='Chart timeframe for the backtest (e.g., M1, H1, D1)', max_length=10),
        ),
    ]
