# Generated by Django 5.1.7 on 2025-08-10 03:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_backtestrun_random_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slippage_model', models.CharField(choices=[('NONE', 'None'), ('FIXED', 'Fixed Ticks'), ('PERCENTAGE', 'Percentage')], default='NONE', max_length=20)),
                ('slippage_value', models.FloatField(default=0, help_text='Value for slippage (e.g., ticks or percentage)')),
                ('commission_units', models.CharField(choices=[('PER_TRADE', 'Per Trade'), ('PER_LOT', 'Per Lot')], default='PER_TRADE', max_length=20)),
                ('commission_per_unit', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('spread_pips', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='backtestconfig',
            name='slippage_ms',
        ),
        migrations.RemoveField(
            model_name='backtestconfig',
            name='slippage_r',
        ),
        migrations.AddField(
            model_name='backtestconfig',
            name='execution_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bots.executionconfig'),
        ),
    ]
