# Generated by Django 5.1.7 on 2025-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_instrument_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='instrument_symbol',
            field=models.CharField(blank=True, help_text='The trading instrument symbol this bot targets, e.g., EUR_USD, XAUUSD', max_length=50, null=True),
        ),
    ]
