# Generated by Django 5.1.7 on 2025-06-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_alter_bot_instrument_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='instrument_symbol',
        ),
        migrations.AddField(
            model_name='backtestrun',
            name='instrument_symbol',
            field=models.CharField(default='', help_text='The trading instrument symbol for this backtest run', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liverun',
            name='instrument_symbol',
            field=models.CharField(default='Default', help_text='The trading instrument symbol for this live run', max_length=50),
            preserve_default=False,
        ),
    ]
