# Generated by Django 5.1.7 on 2025-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_bot_strategy_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='progress',
            field=models.IntegerField(default=0, help_text='Backtest progress percentage'),
        ),
    ]
