# Generated by Django 5.1.7 on 2025-08-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_executionconfig_remove_backtestconfig_slippage_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botversion',
            name='strategy_graph',
            field=models.JSONField(blank=True, help_text='JSON representation of the no-code strategy graph', null=True),
        ),
    ]
