# Generated by Django 5.1.7 on 2025-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_botversion_strategy_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='botversion',
            name='version_name',
            field=models.CharField(blank=True, help_text='A user-friendly name for this version.', max_length=255, null=True),
        ),
    ]
