# Generated by Django 5.1.7 on 2025-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_remove_bot_instrument_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestrun',
            name='simulated_trades_log',
            field=models.JSONField(blank=True, default=list, help_text='Log of all simulated trades', null=True),
        ),
    ]
