# Generated by Django 5.1.7 on 2025-07-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_botversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botversion',
            unique_together=set(),
        ),
    ]
