# Generated by Django 5.1.7 on 2025-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_botversion_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestconfig',
            name='name',
            field=models.CharField(blank=True, help_text='User-defined name for this backtest config', max_length=255, null=True),
        ),
    ]
