# Generated by Django 5.1.7 on 2025-07-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_backtestconfig_timeframe'),
        ('bots', '0005_alter_botversion_unique_together'),
    ]

    operations = [
    ]
