# Generated by Django 5.1.7 on 2025-08-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
        ('bots', '0006_backtestconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverun',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_runs', to='accounts.account'),
        ),
    ]
