# Generated by Django 5.1.7 on 2025-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_liverun_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverun',
            name='timeframe',
            field=models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Hour'), ('H4', '4 Hours'), ('D1', '1 Day')], default='M1', help_text='Chart timeframe for the live run (e.g., M1, H1, D1)', max_length=10),
        ),
    ]
