# Generated by Django 5.1.7 on 2025-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_liverun_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverun',
            name='decision_mode',
            field=models.CharField(choices=[('CANDLE', 'On Candle Close'), ('TICK', 'On Each Tick')], default='CANDLE', help_text='Whether to evaluate strategy on candle close or each tick.', max_length=10),
        ),
    ]
