# Generated by GitHub Copilot on 2025-08-18
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_merge_backtestdecisiontrace_linearize'),
    ]

    operations = [
        # Neutralized placeholder migration to avoid conflicts with canonical BacktestDecisionTrace migrations
    ]
