# Generated by Django 5.1.7 on 2025-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_liverun_decision_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='liverun',
            name='last_action_at',
            field=models.DateTimeField(blank=True, help_text='Last time an action was executed', null=True),
        ),
        migrations.AddField(
            model_name='liverun',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat timestamp from live_loop', null=True),
        ),
        migrations.AddField(
            model_name='liverun',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task id executing this LiveRun', max_length=64, null=True),
        ),
    ]
