# Generated by GitHub Copilot on 2025-08-18
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_liverun_last_action_at_liverun_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestDecisionTrace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True)),
                ('bar_index', models.IntegerField(db_index=True)),
                ('symbol', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=10)),
                ('section', models.CharField(blank=True, help_text='entry|exit|filter|risk|fill|engine', max_length=32, null=True)),
                ('kind', models.CharField(help_text='Atom kind, e.g., condition_eval, filter_result, risk_check, order, fill, state', max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='Compact JSON payload of the trace atom')),
                ('idx', models.IntegerField(blank=True, help_text='Stable order within the bar if needed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backtest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_traces', to='bots.backtestrun')),
            ],
            options={
                'verbose_name': 'Backtest Decision Trace',
                'verbose_name_plural': 'Backtest Decision Traces',
                'ordering': ['backtest_run', 'bar_index', 'idx', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='backtestdecisiontrace',
            index=models.Index(fields=['backtest_run', 'bar_index'], name='bots_backtest_bar_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestdecisiontrace',
            index=models.Index(fields=['backtest_run', 'ts'], name='bots_backtest_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestdecisiontrace',
            index=models.Index(fields=['backtest_run', 'section'], name='bots_backtest_section_idx'),
        ),
    ]
