# Generated by Django 5.1.7 on 2025-08-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_backtestdecisiontrace'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backtestdecisiontrace',
            new_name='bots_backte_backtes_14b9b1_idx',
            old_name='bots_backtest_bar_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestdecisiontrace',
            new_name='bots_backte_backtes_ee6a06_idx',
            old_name='bots_backtest_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='backtestdecisiontrace',
            new_name='bots_backte_backtes_32b5b5_idx',
            old_name='bots_backtest_section_idx',
        ),
        migrations.AddField(
            model_name='backtestconfig',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backtest_configs', to='bots.bot'),
        ),
    ]
