# Generated by Django 5.1.7 on 2025-03-29 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=10)),
                ('indicator_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('max_trade_risk', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_open_positions', models.IntegerField(default=3)),
                ('enforce_cooldowns', models.BooleanField(default=True)),
                ('consecutive_loss_limit', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_settings', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=10)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=10)),
                ('profit_target', models.DecimalField(decimal_places=5, max_digits=10)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('projected_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('projected_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('rr_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trade_status', models.CharField(default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('trade_timeframe', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('chart_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='trading.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_trades', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_rr_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('profit_factor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
