# Generated by Django 5.1.7 on 2025-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
