# Generated by Django 5.1.7 on 2025-03-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_trade_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='deal_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
