# Generated by Django 5.1.7 on 2025-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_trade_deal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='position_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='swap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
