# Generated by Django 5.1.7 on 2025-03-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade_commission_trade_position_id_trade_swap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeJournal',
        ),
    ]
