# Generated by Django 5.1.7 on 2025-03-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_delete_tradejournal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskManagement',
        ),
    ]
