# Generated by Django 5.1.7 on 2025-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_delete_riskmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trader',
            field=models.CharField(blank=True, help_text='The identifier or name of the user executing the trade.', max_length=100, null=True),
        ),
    ]
