# Generated by Django 5.1.7 on 2025-04-21 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_active'),
        ('trading', '0007_trade_trader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP', 'Stop'), ('STOP_LIMIT', 'Stop‑Limit')], max_length=12)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price', models.DecimalField(blank=True, decimal_places=5, help_text='Limit/stop price. Null for market orders.', max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('time_in_force', models.CharField(choices=[('GTC', 'Good‑Till‑Cancel'), ('GTD', 'Good‑Till‑Date'), ('IOC', 'Immediate‑Or‑Cancel'), ('FOK', 'Fill‑Or‑Kill')], default='GTC', max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partial', 'Partially filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('broker_order_id', models.BigIntegerField(blank=True, null=True)),
                ('broker_deal_id', models.BigIntegerField(blank=True, null=True)),
                ('filled_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('filled_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.account')),
                ('trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='trading.trade')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='trading_ord_account_f89586_idx'), models.Index(fields=['broker_order_id'], name='trading_ord_broker__6cd630_idx')],
            },
        ),
    ]
