# Generated by Django 5.1.7 on 2025-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
