# Generated by Django 5.1.7 on 2025-04-26 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_trade_entry_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField()),
                ('target_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('target_volume', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('hit_at', models.DateTimeField(blank=True, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='trading.trade')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('trade', 'rank')},
            },
        ),
    ]
