# Generated by Django 5.1.7 on 2025-04-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_profittarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='indicators',
            field=models.JSONField(blank=True, help_text='Snapshot of precomputed indicators at entry', null=True),
        ),
    ]
