# Generated by Django 5.1.7 on 2025-05-16 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_trade_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='trading.trade'),
        ),
    ]
