# Generated by Django 5.1.7 on 2025-05-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_alter_order_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='broker_deal_reason_code',
            field=models.IntegerField(blank=True, help_text='Platform-specific reason code for the deal (e.g., MT5 DEAL_REASON_CLIENT)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission for this specific deal', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profit of this specific deal', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='swap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Swap for this specific deal', max_digits=10, null=True),
        ),
    ]
