# Generated by Django 5.1.7 on 2025-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_order_broker_deal_reason_code_order_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closure_reason',
            field=models.CharField(blank=True, help_text='Application-specific reason for order closure', max_length=255, null=True),
        ),
    ]
