# Generated by Django 5.1.7 on 2025-05-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_order_closure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_target',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
    ]
