# Generated by Django 5.1.7 on 2025-06-03 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_alter_trade_entry_price_alter_trade_profit_target_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='exchange',
            field=models.CharField(blank=True, help_text='e.g., NASDAQ, NYSE, FXCM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, this watchlist item is visible to all users.'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'is_global'], name='trading_wat_user_id_bc4da3_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['is_global'], name='trading_wat_is_glob_67dfd9_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('user', 'instrument', 'exchange'), name='unique_user_instrument_exchange_watchlist'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('instrument', 'exchange'), name='unique_global_instrument_exchange_watchlist'),
        ),
    ]
