# Generated by Django 5.1.7 on 2025-06-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_watchlist_exchange_watchlist_is_global_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSpecification',
            fields=[
                ('symbol', models.CharField(help_text='The trading instrument symbol, e.g., EURUSD, XAUUSD', max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', help_text='Description of the instrument', max_length=255)),
                ('source_platform', models.CharField(blank=True, help_text='Platform from which this spec was fetched, e.g., MT5, cTrader', max_length=50)),
                ('contract_size', models.DecimalField(blank=True, decimal_places=5, help_text='Number of units in one standard lot (e.g., 100000 for EURUSD)', max_digits=20, null=True)),
                ('base_currency', models.CharField(blank=True, help_text='Base currency of the pair (e.g., EUR for EURUSD)', max_length=20)),
                ('quote_currency', models.CharField(blank=True, help_text='Quote currency of the pair (e.g., USD for EURUSD)', max_length=20)),
                ('margin_currency', models.CharField(blank=True, help_text='Currency used for margin calculation', max_length=20)),
                ('min_volume', models.DecimalField(blank=True, decimal_places=5, help_text='Minimum trade volume in lots', max_digits=12, null=True)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=5, help_text='Maximum trade volume in lots', max_digits=12, null=True)),
                ('volume_step', models.DecimalField(blank=True, decimal_places=5, help_text='Smallest increment for trade volume in lots', max_digits=12, null=True)),
                ('tick_size', models.DecimalField(blank=True, decimal_places=10, help_text='Smallest possible price change (e.g., 0.00001 for EURUSD)', max_digits=15, null=True)),
                ('tick_value', models.DecimalField(blank=True, decimal_places=5, help_text="Value of one 'tick_size' movement for one full lot, in account currency", max_digits=15, null=True)),
                ('digits', models.PositiveSmallIntegerField(blank=True, help_text='Number of decimal places for price display', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instrument Specification',
                'verbose_name_plural': 'Instrument Specifications',
                'ordering': ['symbol'],
            },
        ),
    ]
