# Generated by Django 5.1.7 on 2025-08-02 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
        ('trading', '0017_instrumentspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_data', to='accounts.account')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
