# Generated by Django 5.1.7 on 2025-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_equitydatapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='projected_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='projected_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rr_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
