# Generated by Django 5.1.7 on 2025-08-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_order_projected_loss_order_projected_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='max_drawdown',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum loss experienced by the trade', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='max_runup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum profit reached by the trade', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tradeperformance',
            name='max_account_drawdown',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum account drawdown percentage or value', max_digits=15),
        ),
    ]
