# Generated by Django 5.1.7 on 2025-08-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_trade_max_drawdown_trade_max_runup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentspecification',
            options={},
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='digits',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='max_volume',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='min_volume',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='tick_size',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='tick_value',
        ),
        migrations.RemoveField(
            model_name='instrumentspecification',
            name='volume_step',
        ),
        migrations.DeleteModel(
            name='EquityDataPoint',
        ),
    ]
