# Generated by Django 5.1.7 on 2025-08-06 05:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
        ('trading', '0021_alter_instrumentspecification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentspecification',
            options={'ordering': ['symbol'], 'verbose_name': 'Instrument Specification', 'verbose_name_plural': 'Instrument Specifications'},
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='digits',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of decimal places for price display', null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='max_volume',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Maximum trade volume in lots', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='min_volume',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Minimum trade volume in lots', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='tick_size',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Smallest possible price change (e.g., 0.00001 for EURUSD)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='tick_value',
            field=models.DecimalField(blank=True, decimal_places=5, help_text="Value of one 'tick_size' movement for one full lot, in account currency", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='instrumentspecification',
            name='volume_step',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Smallest increment for trade volume in lots', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='EquityDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_data', to='accounts.account')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
