# Generated by Django 5.1.7 on 2025-08-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
        ('bots', '0009_liverun_decision_mode'),
        ('trading', '0022_alter_instrumentspecification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='bot_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='bots.botversion'),
        ),
        migrations.AddField(
            model_name='trade',
            name='correlation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='live_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='bots.liverun'),
        ),
        migrations.AddField(
            model_name='trade',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AI', 'AI'), ('BOT', 'Bot'), ('BACKTEST', 'Backtest')], default='MANUAL', max_length=16),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['bot_version', 'created_at'], name='trading_tra_bot_ver_8f24b4_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['live_run', 'created_at'], name='trading_tra_live_ru_0d1aff_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['source', 'created_at'], name='trading_tra_source_988021_idx'),
        ),
    ]
