# Generated by Django 5.1.7 on 2025-08-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_trade_bot_version_trade_correlation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='close_reason',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='close_subreason',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='close_reason',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='close_subreason',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
