# Generated by Django 5.1.7 on 2025-08-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_order_close_reason_order_close_subreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True),
        ),
    ]
