# Generated by Django 5.1.7 on 2025-08-23 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ctraderaccount_ctid_user_id_and_more'),
        ('trading', '0025_trade_close_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_links', to='accounts.account')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='trading.watchlist')),
            ],
        ),
        migrations.AddField(
            model_name='watchlist',
            name='accounts',
            field=models.ManyToManyField(blank=True, help_text='Accounts this watchlist item applies to. Leave empty for user-general items.', related_name='watchlists', through='trading.WatchlistAccountLink', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='watchlistaccountlink',
            index=models.Index(fields=['account'], name='trading_wat_account_8ff359_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistaccountlink',
            index=models.Index(fields=['watchlist'], name='trading_wat_watchli_f1ff7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlistaccountlink',
            constraint=models.UniqueConstraint(fields=('watchlist', 'account'), name='unique_watchlist_account_link'),
        ),
    ]
