from rest_framework import serializers
from .models import Bot, BotVersion, BacktestConfig, BacktestRun, LiveRun
from accounts.serializers import AccountSerializer # Assuming you have this
from django.contrib.auth import get_user_model

User = get_user_model()

class UserSimpleSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['id', 'username', 'email']

class BotSerializer(serializers.ModelSerializer):
    # account = AccountSerializer(read_only=True) # Or use PrimaryKeyRelatedField for writes
    account_id = serializers.UUIDField(source='account.id', allow_null=True, required=False, write_only=True)
    created_by = UserSimpleSerializer(read_only=True)
    created_by_id = serializers.IntegerField(write_only=True, required=False, allow_null=True)

    class Meta:
        model = Bot
        fields = [
            'id', 'name', 'account', 'account_id', 'strategy_template', # instrument_symbol removed
            'is_active', 'created_by', 'created_by_id', 'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at', 'account', 'created_by']
    
    def create(self, validated_data):
        account_id = validated_data.pop('account_id', None)
        created_by_id = validated_data.pop('created_by_id', None)
        
        if account_id:
            validated_data['account_id'] = account_id
        
        # Set created_by from request user if not provided
        request_user = self.context['request'].user
        if request_user and request_user.is_authenticated:
            if created_by_id is None: # only set if not explicitly provided
                 validated_data['created_by'] = request_user
            elif created_by_id != request_user.id and not request_user.is_staff: # Non-staff cannot set other users
                raise serializers.ValidationError("You can only create bots for yourself.")
            else: # staff can set other users
                 validated_data['created_by_id'] = created_by_id
        elif created_by_id is None: # No request user and no id provided
            raise serializers.ValidationError("User context is required to create a bot or specify created_by_id.")
        else: # No request user but id provided (e.g. system process)
            validated_data['created_by_id'] = created_by_id
            
        return super().create(validated_data)

class BotVersionSerializer(serializers.ModelSerializer):
    bot_name = serializers.CharField(source='bot.name', read_only=True)

    class Meta:
        model = BotVersion
        fields = ['id', 'bot', 'bot_name', 'code_hash', 'params', 'notes', 'created_at']
        read_only_fields = ['id', 'code_hash', 'created_at', 'bot_name'] # code_hash is generated by service

class BacktestConfigSerializer(serializers.ModelSerializer):
    bot_version_info = serializers.CharField(source='bot_version.__str__', read_only=True)

    class Meta:
        model = BacktestConfig
        fields = [
            'id', 'bot_version', 'bot_version_info', 'risk_json', 
            'slippage_ms', 'slippage_r', 'label', 'created_at'
        ]
        read_only_fields = ['id', 'created_at', 'bot_version_info']

class BacktestRunSerializer(serializers.ModelSerializer):
    config_label = serializers.CharField(source='config.label', read_only=True, allow_null=True)
    bot_name = serializers.CharField(source='config.bot_version.bot.name', read_only=True)

    class Meta:
        model = BacktestRun
        fields = [
            'id', 'config', 'instrument_symbol', 'config_label', 'bot_name', 'data_window_start', 
            'data_window_end', 'equity_curve', 'stats', 'simulated_trades_log', 'status', 'created_at'
        ]
        read_only_fields = ['id', 'instrument_symbol', 'equity_curve', 'stats', 'simulated_trades_log', 'created_at', 'config_label', 'bot_name']

class LiveRunSerializer(serializers.ModelSerializer):
    bot_name = serializers.CharField(source='bot_version.bot.name', read_only=True)
    bot_version_created_at = serializers.DateTimeField(source='bot_version.created_at', read_only=True)

    class Meta:
        model = LiveRun
        fields = [
            'id', 'bot_version', 'instrument_symbol', 'bot_name', 'bot_version_created_at', 'started_at', 
            'stopped_at', 'status', 'pnl_r', 'drawdown_r', 'last_error'
        ]
        read_only_fields = ['id', 'instrument_symbol', 'started_at', 'stopped_at', 'pnl_r', 'drawdown_r', 'last_error', 'bot_name', 'bot_version_created_at']

# Serializers for specific actions
class LaunchBacktestSerializer(serializers.Serializer):
    bot_version_id = serializers.UUIDField()
    backtest_config_id = serializers.UUIDField()
    instrument_symbol = serializers.CharField(max_length=50)
    data_window_start = serializers.DateTimeField()
    data_window_end = serializers.DateTimeField()

    def validate(self, data):
        if data['data_window_start'] >= data['data_window_end']:
            raise serializers.ValidationError("data_window_end must be after data_window_start.")
        # Could add validation to check if BotVersion and BacktestConfig exist and are related
        return data

class BotVersionCreateSerializer(serializers.Serializer):
    bot_id = serializers.UUIDField()
    # strategy_code as a string field, or expect file upload handled by view
    strategy_file_content = serializers.CharField(write_only=True, help_text="Full content of the strategy's .py file. If empty, uses the bot's default template.", allow_blank=True, required=False)
    params = serializers.JSONField()
    notes = serializers.CharField(required=False, allow_blank=True, allow_null=True)

class StartLiveRunSerializer(serializers.Serializer):
    bot_version_id = serializers.UUIDField()
    instrument_symbol = serializers.CharField(max_length=50)

# --- Serializers for Charting Data ---

class BacktestOhlcvDataSerializer(serializers.Serializer):
    # For ApexCharts, OHLC data is often [{ x: timestamp, y: [o, h, l, c] }]
    # We can achieve this structure in the view or a custom serializer field if needed,
    # but for now, let's serialize individual fields.
    # The view can then structure it.
    timestamp = serializers.DateTimeField()
    open = serializers.DecimalField(max_digits=19, decimal_places=8)
    high = serializers.DecimalField(max_digits=19, decimal_places=8)
    low = serializers.DecimalField(max_digits=19, decimal_places=8)
    close = serializers.DecimalField(max_digits=19, decimal_places=8)
    volume = serializers.IntegerField(required=False, allow_null=True)

    # If we were using a ModelSerializer:
    # class Meta:
    #     model = BacktestOhlcvData
    #     fields = ['timestamp', 'open', 'high', 'low', 'close', 'volume']

class BacktestIndicatorDataSerializer(serializers.Serializer):
    timestamp = serializers.DateTimeField()
    indicator_name = serializers.CharField()
    value = serializers.DecimalField(max_digits=19, decimal_places=8)

    # If we were using a ModelSerializer:
    # class Meta:
    #     model = BacktestIndicatorData
    #     fields = ['timestamp', 'indicator_name', 'value']


class BacktestTradeMarkerSerializer(serializers.Serializer):
    """
    Serializes trade information from BacktestRun.simulated_trades_log 
    into a format suitable for chart markers.
    """
    entry_timestamp = serializers.DateTimeField()
    entry_price = serializers.FloatField()
    exit_timestamp = serializers.DateTimeField(allow_null=True) # Can be null if still open (though not for backtests)
    exit_price = serializers.FloatField(allow_null=True)
    direction = serializers.CharField() # BUY or SELL
    volume = serializers.FloatField()
    pnl = serializers.FloatField(required=False)
    closure_reason = serializers.CharField(required=False)
    # id = serializers.CharField() # Original position ID

class BacktestChartDataSerializer(serializers.Serializer):
    """
    Combines OHLCV, indicators, and trade markers for a backtest run.
    This serializer will be populated in the view.
    """
    ohlcv_data = BacktestOhlcvDataSerializer(many=True, read_only=True)
    indicator_data = serializers.DictField( # Keyed by indicator name, value is list of points
        child=BacktestIndicatorDataSerializer(many=True, read_only=True),
        read_only=True
    )
    trade_markers = BacktestTradeMarkerSerializer(many=True, read_only=True)
    # Could also include BacktestRun metadata if needed
    # backtest_run_id = serializers.UUIDField(read_only=True)
    # instrument_symbol = serializers.CharField(read_only=True)
    # data_window_start = serializers.DateTimeField(read_only=True)
    # data_window_end = serializers.DateTimeField(read_only=True)
