# Generated by Django 5.1.7 on 2025-03-30 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0005_delete_tradejournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('chart_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('strategy_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('emotional_state', models.CharField(blank=True, max_length=50, null=True)),
                ('market_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='trading.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeJournalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='journal_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trade_journal.tradejournal')),
            ],
        ),
    ]
