# Generated by Django 5.1.7 on 2025-05-25 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradejournalattachment',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='trade_journal.tradejournal'),
        ),
    ]
