# Generated by Django 5.1.7 on 2025-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0002_alter_tradejournalattachment_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradejournal',
            name='market_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
