# Generated by Django 5.1.7 on 2025-07-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_journal', '0003_alter_tradejournal_market_condition'),
        ('trading', '0017_instrumentspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradejournal',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='trading.order'),
        ),
        migrations.AlterField(
            model_name='tradejournal',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='trading.trade'),
        ),
    ]
