# Generated by Django 5.1.7 on 2025-03-30 06:40

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('max_trade_risk', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_open_positions', models.IntegerField(default=3)),
                ('enforce_cooldowns', models.BooleanField(default=True)),
                ('consecutive_loss_limit', models.IntegerField(default=3)),
                ('cooldown_period', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('max_lot_size', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_open_trades_same_symbol', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_settings', to='accounts.account')),
            ],
        ),
    ]
