# Generated by Django 5.1.7 on 2025-05-11 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profittakingprofile'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmanagement',
            name='default_tp_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.profittakingprofile'),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='risk_percent',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Default risk percent per trade (e.g. 0.30 = 0.3%)', max_digits=5),
        ),
    ]
