# Generated by Django 5.1.7 on 2025-07-31 11:55

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profittakingprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='simple_id',
            field=models.IntegerField(default=accounts.models.generate_six_digit_code),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'simple_id')},
        ),
    ]
