# Generated by Django 5.1.7 on 2025-07-31 12:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_simple_id_alter_account_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='simple_id',
            field=models.IntegerField(default=accounts.models.generate_six_digit_code),
        ),
    ]
