# Generated by Django 5.1.7 on 2025-07-31 12:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_simple_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='simple_id',
            field=models.IntegerField(db_index=True, default=accounts.models.generate_six_digit_code),
        ),
    ]
