# Generated by Django 5.1.7 on 2025-08-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctraderaccount',
            name='ctid_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ctraderaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
