# Generated by Django 5.1.7 on 2025-07-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartprofile',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
