# Generated by Django 5.1.7 on 2025-07-31 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(default='', max_length=100)),
                ('impact', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('event', models.CharField()),
                ('actual', models.CharField(blank=True, max_length=200, null=True)),
                ('previous', models.CharField(blank=True, max_length=200, null=True)),
                ('forecast', models.CharField(blank=True, max_length=200, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('graph', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundamental.currency')),
            ],
        ),
    ]
