# Generated by Django 5.1.7 on 2025-08-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundamental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='economiccalendar',
            old_name='date',
            new_name='event_time',
        ),
        migrations.RemoveField(
            model_name='economiccalendar',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='economiccalendar',
            name='time',
        ),
    ]
