# Generated by Django 5.1.7 on 2025-08-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundamental', '0002_rename_date_economiccalendar_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economiccalendar',
            name='graph',
        ),
        migrations.RemoveField(
            model_name='economiccalendar',
            name='source_url',
        ),
    ]
