# Generated by Django 5.1.7 on 2025-08-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundamental', '0003_remove_economiccalendar_graph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economiccalendar',
            name='country',
        ),
    ]
