# Generated by Django 5.1.7 on 2025-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundamental', '0004_remove_economiccalendar_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=500, null=True, verbose_name='Headline')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Time')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='Source')),
                ('url', models.URLField(max_length=900, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
        ),
    ]
