# Generated by Django 5.1.7 on 2025-06-29 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('timeframe', models.CharField(db_index=True, max_length=3)),
                ('candle_close', models.DateTimeField(db_index=True)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('side', 'Sideways')], max_length=4)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('signal', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('none', 'None')], default='none', max_length=8)),
                ('analysis', models.JSONField()),
                ('data_hash', models.CharField(max_length=64)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('snapshot_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'TA Analysis',
                'verbose_name_plural': 'TA Analyses',
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-candle_close'], name='ta_taanalys_symbol_6ecbfd_idx')],
                'unique_together': {('symbol', 'timeframe', 'candle_close')},
            },
        ),
    ]
