# Generated by Django 5.1.7 on 2025-06-01 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('TREND_CONTINUATION', 'Trend Continuation'), ('VWAP_CONDITIONAL', 'VWAP Conditional'), ('ATR_SCENARIO', 'ATR Scenario')], max_length=100)),
                ('target_timeframe', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FETCHING_DATA', 'Fetching Data'), ('RESAMPLING_DATA', 'Resampling Data'), ('CALCULATING_INDICATORS', 'Calculating Indicators'), ('RUNNING_ANALYSIS', 'Running Analysis'), ('COMPLETED_SUCCESS', 'Completed Successfully'), ('COMPLETED_FAIL', 'Completed with Failure')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('exchange', models.CharField(default='FXCM', max_length=50)),
                ('base_timeframe', models.CharField(default='M1', max_length=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('data_status', models.CharField(choices=[('PENDING_INITIAL_DOWNLOAD', 'Pending Initial Download'), ('AVAILABLE', 'Available'), ('UPDATING', 'Updating'), ('ERROR', 'Error')], default='PENDING_INITIAL_DOWNLOAD', max_length=30)),
                ('is_major', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='analysis.analysisjob')),
                ('result_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.instrument'),
        ),
    ]
