# Generated by Django 5.1.7 on 2025-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='analysis_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='indicator_configs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
