# Generated by Django 5.1.7 on 2025-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisjob_analysis_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='analysis_type',
            field=models.CharField(choices=[('TREND_CONTINUATION', 'Trend Continuation'), ('VWAP_CONDITIONAL', 'VWAP Conditional'), ('ATR_SCENARIO', 'ATR Scenario'), ('ATR_SQUEEZE_BREAKOUT', 'ATR Squeeze Breakout')], max_length=100),
        ),
    ]
