# Generated by Django 5.1.7 on 2025-08-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_analysisjob_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
