# Generated by Django 5.1.7 on 2025-07-23 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('user_first_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('external_session_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('external_execution_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('external_execution_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('is_globally_shared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'version', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SessionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_executions', to='AI.execution')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='AI.chatsession')),
            ],
            options={
                'unique_together': {('session', 'execution')},
            },
        ),
    ]
