# Generated by Django 5.1.7 on 2025-07-28 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='prompt',
            new_name='user_prompt',
        ),
        migrations.AddField(
            model_name='prompt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
