# Generated by Django 5.1.7 on 2025-08-04 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_rename_prompt_prompt_user_prompt_prompt_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
