# Generated by Django 5.1.7 on 2025-08-04 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_alter_prompt_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('name', 'user')},
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='version',
        ),
    ]
