# Generated by Django 5.1.7 on 2025-08-04 07:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0004_alter_prompt_unique_together_remove_prompt_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=50)),
                ('recurrence', models.CharField(choices=[('MINUTELY', 'Minutely'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MINUTELY', max_length=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('excluded_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=255), blank=True, default=list, size=None)),
                ('excluded_time_ranges', models.JSONField(blank=True, default=list)),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='AI.chatsession')),
            ],
        ),
    ]
