# Generated by Django 5.1.7 on 2025-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0005_sessionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionschedule',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
