# Generated by Django 5.1.7 on 2025-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0006_alter_sessionschedule_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionschedule',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('MINUTELY', 'Minutely'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MINUTELY', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sessionschedule',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
