# Generated by Django 5.1.7 on 2025-08-04 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0008_sessionschedule_task_sessionscheduletask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionschedule',
            name='excluded_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
