# Generated by Django 5.1.7 on 2025-08-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0009_alter_sessionschedule_excluded_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionscheduletask',
            unique_together=set(),
        ),
    ]
