# Generated by Django 5.1.7 on 2025-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0010_alter_sessionscheduletask_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionscheduletask',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
