# Generated by Django 5.1.7 on 2025-08-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0011_alter_sessionscheduletask_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('CHAT', 'Chat'), ('BOT_BUILDER', 'Bot Builder')], default='CHAT', max_length=50),
        ),
    ]
