# Generated by Django 5.1.7 on 2025-08-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0012_chatsession_session_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionschedule',
            name='recurrence',
        ),
    ]
