# Generated by Django 5.1.7 on 2025-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0013_remove_sessionschedule_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionschedule',
            name='interval_every',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='interval_period',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('microseconds', 'Microseconds')], max_length=24, null=True),
        ),
    ]
