# Generated by Django 5.1.7 on 2025-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0014_sessionschedule_interval_every_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
