# Generated by Django 5.1.7 on 2025-08-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0015_chatsession_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionschedule',
            name='interval_period',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Hours', 'Hours'), ('Minutes', 'Minutes'), ('Seconds', 'Seconds'), ('Microseconds', 'Microseconds')], max_length=24, null=True),
        ),
    ]
