# Generated by Django 5.1.7 on 2025-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0016_alter_sessionschedule_interval_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionschedule',
            name='interval_period',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds'), ('microseconds', 'Microseconds')], max_length=24, null=True),
        ),
    ]
