name: Contract Tests

on:
  pull_request:
    paths:
      - 'trades/views.py'
      - 'accounts/consumers.py'
      - 'tests/test_contract_views_exist.py'
      - 'scripts/check_critical_symbols.py'
      - '.github/workflows/contract-tests.yml'
  push:
    branches: [ main, master, dev*, develop ]
    paths:
      - 'trades/views.py'
      - 'accounts/consumers.py'
      - 'tests/test_contract_views_exist.py'
      - 'scripts/check_critical_symbols.py'
      - '.github/workflows/contract-tests.yml'

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-django

      - name: Run contract tests only
        run: |
          pytest -q tests/test_contract_views_exist.py
